-- Create Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  supplier TEXT,
  cost NUMERIC DEFAULT 0,
  price NUMERIC DEFAULT 0,
  stock INTEGER DEFAULT 0,
  status TEXT,
  orders INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Orders table
CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  customer TEXT NOT NULL,
  product TEXT,
  date TEXT,
  total NUMERIC DEFAULT 0,
  status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Suppliers table
CREATE TABLE suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT,
  phone TEXT,
  products_count INTEGER DEFAULT 0,
  rating NUMERIC DEFAULT 0,
  status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Marketing Campaigns table
CREATE TABLE campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  platform TEXT,
  budget NUMERIC DEFAULT 0,
  spent NUMERIC DEFAULT 0,
  revenue NUMERIC DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0,
  status TEXT,
  start_date TEXT,
  end_date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Emails/Messages table
CREATE TABLE outreach (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  type TEXT,
  date TEXT,
  sent INTEGER DEFAULT 0,
  opened INTEGER DEFAULT 0,
  clicked INTEGER DEFAULT 0,
  revenue NUMERIC DEFAULT 0,
  status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial mock data for Products
INSERT INTO products (name, supplier, cost, price, stock, status, orders)
VALUES 
('Deri Cüzdan', 'Tedarikçi A', 85, 249, 42, 'aktif', 18),
('Kablosuz Kulaklık', 'Tedarikçi B', 320, 799, 15, 'aktif', 34),
('Ahşap Saat', 'Tedarikçi A', 210, 549, 0, 'tükendi', 7),
('Seramik Bardak', 'Tedarikçi C', 45, 129, 88, 'aktif', 52),
('Çanta (Hasır)', 'Tedarikçi B', 130, 349, 5, 'az stok', 23);

-- Insert initial mock data for Orders
INSERT INTO orders (id, customer, product, date, total, status)
VALUES 
('#1042', 'Ayşe K.', 'Deri Cüzdan', '08 Mar', 249, 'kargoda'),
('#1041', 'Mehmet T.', 'Kablosuz Kulaklık', '08 Mar', 799, 'hazırlanıyor'),
('#1040', 'Zeynep A.', 'Seramik Bardak', '07 Mar', 258, 'teslim edildi'),
('#1039', 'Can D.', 'Çanta (Hasır)', '07 Mar', 349, 'teslim edildi'),
('#1038', 'Elif S.', 'Kablosuz Kulaklık', '06 Mar', 799, 'teslim edildi');
